/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.hopper.language.portugol.PortugolPackage#getAddExpression()
 * @model
 * @generated
 */
public interface AddExpression extends Expression
{
} // AddExpression
