/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block Procedure</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hopper.language.portugol.BlockProcedure#getProcedure <em>Procedure</em>}</li>
 * </ul>
 *
 * @see org.hopper.language.portugol.PortugolPackage#getBlockProcedure()
 * @model
 * @generated
 */
public interface BlockProcedure extends BlockSubPrograms
{
  /**
   * Returns the value of the '<em><b>Procedure</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Procedure</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Procedure</em>' containment reference.
   * @see #setProcedure(ProcedureName)
   * @see org.hopper.language.portugol.PortugolPackage#getBlockProcedure_Procedure()
   * @model containment="true"
   * @generated
   */
  ProcedureName getProcedure();

  /**
   * Sets the value of the '{@link org.hopper.language.portugol.BlockProcedure#getProcedure <em>Procedure</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Procedure</em>' containment reference.
   * @see #getProcedure()
   * @generated
   */
  void setProcedure(ProcedureName value);

} // BlockProcedure
