/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.hopper.language.portugol.PortugolPackage#getConstant()
 * @model
 * @generated
 */
public interface Constant extends EObject
{
} // Constant
