/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression Variable</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hopper.language.portugol.ExpressionVariable#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.hopper.language.portugol.PortugolPackage#getExpressionVariable()
 * @model
 * @generated
 */
public interface ExpressionVariable extends Expression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(VarName)
   * @see org.hopper.language.portugol.PortugolPackage#getExpressionVariable_Value()
   * @model
   * @generated
   */
  VarName getValue();

  /**
   * Sets the value of the '{@link org.hopper.language.portugol.ExpressionVariable#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(VarName value);

} // ExpressionVariable
