/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>If Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hopper.language.portugol.IfStatement#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.hopper.language.portugol.IfStatement#getCommands <em>Commands</em>}</li>
 *   <li>{@link org.hopper.language.portugol.IfStatement#getElseCommands <em>Else Commands</em>}</li>
 * </ul>
 *
 * @see org.hopper.language.portugol.PortugolPackage#getIfStatement()
 * @model
 * @generated
 */
public interface IfStatement extends AbstractCommand
{
  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(Expression)
   * @see org.hopper.language.portugol.PortugolPackage#getIfStatement_Expr()
   * @model containment="true"
   * @generated
   */
  Expression getExpr();

  /**
   * Sets the value of the '{@link org.hopper.language.portugol.IfStatement#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(Expression value);

  /**
   * Returns the value of the '<em><b>Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.hopper.language.portugol.AbstractCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Commands</em>' containment reference list.
   * @see org.hopper.language.portugol.PortugolPackage#getIfStatement_Commands()
   * @model containment="true"
   * @generated
   */
  EList<AbstractCommand> getCommands();

  /**
   * Returns the value of the '<em><b>Else Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.hopper.language.portugol.AbstractCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Else Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Else Commands</em>' containment reference list.
   * @see org.hopper.language.portugol.PortugolPackage#getIfStatement_ElseCommands()
   * @model containment="true"
   * @generated
   */
  EList<AbstractCommand> getElseCommands();

} // IfStatement
