/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Other Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.hopper.language.portugol.OtherCase#getOtherCaseCommands <em>Other Case Commands</em>}</li>
 *   <li>{@link org.hopper.language.portugol.OtherCase#isBreakStatement <em>Break Statement</em>}</li>
 * </ul>
 *
 * @see org.hopper.language.portugol.PortugolPackage#getOtherCase()
 * @model
 * @generated
 */
public interface OtherCase extends EObject
{
  /**
   * Returns the value of the '<em><b>Other Case Commands</b></em>' containment reference list.
   * The list contents are of type {@link org.hopper.language.portugol.AbstractCommand}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Other Case Commands</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Other Case Commands</em>' containment reference list.
   * @see org.hopper.language.portugol.PortugolPackage#getOtherCase_OtherCaseCommands()
   * @model containment="true"
   * @generated
   */
  EList<AbstractCommand> getOtherCaseCommands();

  /**
   * Returns the value of the '<em><b>Break Statement</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Break Statement</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Break Statement</em>' attribute.
   * @see #setBreakStatement(boolean)
   * @see org.hopper.language.portugol.PortugolPackage#getOtherCase_BreakStatement()
   * @model
   * @generated
   */
  boolean isBreakStatement();

  /**
   * Sets the value of the '{@link org.hopper.language.portugol.OtherCase#isBreakStatement <em>Break Statement</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Break Statement</em>' attribute.
   * @see #isBreakStatement()
   * @generated
   */
  void setBreakStatement(boolean value);

} // OtherCase
