/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.portugol.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.hopper.language.portugol.PortugolPackage;
import org.hopper.language.portugol.WriteCommand;
import org.hopper.language.portugol.WriteParam;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Write Command</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.hopper.language.portugol.impl.WriteCommandImpl#getWriteParam <em>Write Param</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WriteCommandImpl extends AbstractCommandImpl implements WriteCommand
{
  /**
   * The cached value of the '{@link #getWriteParam() <em>Write Param</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWriteParam()
   * @generated
   * @ordered
   */
  protected WriteParam writeParam;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WriteCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PortugolPackage.Literals.WRITE_COMMAND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public WriteParam getWriteParam()
  {
    return writeParam;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWriteParam(WriteParam newWriteParam, NotificationChain msgs)
  {
    WriteParam oldWriteParam = writeParam;
    writeParam = newWriteParam;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, PortugolPackage.WRITE_COMMAND__WRITE_PARAM, oldWriteParam, newWriteParam);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setWriteParam(WriteParam newWriteParam)
  {
    if (newWriteParam != writeParam)
    {
      NotificationChain msgs = null;
      if (writeParam != null)
        msgs = ((InternalEObject)writeParam).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - PortugolPackage.WRITE_COMMAND__WRITE_PARAM, null, msgs);
      if (newWriteParam != null)
        msgs = ((InternalEObject)newWriteParam).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - PortugolPackage.WRITE_COMMAND__WRITE_PARAM, null, msgs);
      msgs = basicSetWriteParam(newWriteParam, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PortugolPackage.WRITE_COMMAND__WRITE_PARAM, newWriteParam, newWriteParam));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PortugolPackage.WRITE_COMMAND__WRITE_PARAM:
        return basicSetWriteParam(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PortugolPackage.WRITE_COMMAND__WRITE_PARAM:
        return getWriteParam();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PortugolPackage.WRITE_COMMAND__WRITE_PARAM:
        setWriteParam((WriteParam)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PortugolPackage.WRITE_COMMAND__WRITE_PARAM:
        setWriteParam((WriteParam)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PortugolPackage.WRITE_COMMAND__WRITE_PARAM:
        return writeParam != null;
    }
    return super.eIsSet(featureID);
  }

} //WriteCommandImpl
