/*
 * generated by Xtext 2.9.0
 */
package org.hopper.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class PortugolStandaloneSetup extends PortugolStandaloneSetupGenerated {

	def static void doSetup() {
		new PortugolStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
