/*
 * generated by Xtext 2.9.0
 */
package org.hopper.language.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.hopper.language.parser.antlr.internal.InternalPortugolParser;
import org.hopper.language.services.PortugolGrammarAccess;

public class PortugolParser extends AbstractAntlrParser {

	@Inject
	private PortugolGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalPortugolParser createParser(XtextTokenStream stream) {
		return new InternalPortugolParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public PortugolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PortugolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
