/**
 * generated by Xtext
 */
package com.hopper.validation;

import com.hopper.validation.AbstractPortugolValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class PortugolValidator extends AbstractPortugolValidator {
}
