/*
* generated by Xtext
*/
package com.hopper.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.hopper.services.PortugolGrammarAccess;

public class PortugolParser extends AbstractContentAssistParser {
	
	@Inject
	private PortugolGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.hopper.ui.contentassist.antlr.internal.InternalPortugolParser createParser() {
		com.hopper.ui.contentassist.antlr.internal.InternalPortugolParser result = new com.hopper.ui.contentassist.antlr.internal.InternalPortugolParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getProgramaAccess().getGroup(), "rule__Programa__Group__0");
					put(grammarAccess.getHEADERAccess().getGroup(), "rule__HEADER__Group__0");
					put(grammarAccess.getModelAccess().getMainAssignment(), "rule__Model__MainAssignment");
					put(grammarAccess.getHEADERAccess().getNameOfProgramAssignment_2(), "rule__HEADER__NameOfProgramAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.hopper.ui.contentassist.antlr.internal.InternalPortugolParser typedParser = (com.hopper.ui.contentassist.antlr.internal.InternalPortugolParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PortugolGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PortugolGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
