/**
 * generated by Xtext 2.9.0
 */
package org.hopper.language.formatting2;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import java.util.Arrays;
import java.util.List;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegionsFinder;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.hopper.language.portugol.AbstractCommand;
import org.hopper.language.portugol.BlockCommand;
import org.hopper.language.portugol.BlockFunction;
import org.hopper.language.portugol.BlockProcedure;
import org.hopper.language.portugol.BlockSubPrograms;
import org.hopper.language.portugol.BreakStatement;
import org.hopper.language.portugol.CaseList;
import org.hopper.language.portugol.DeclarationsBlock;
import org.hopper.language.portugol.Expression;
import org.hopper.language.portugol.ForStatement;
import org.hopper.language.portugol.HeaderBlock;
import org.hopper.language.portugol.IfStatement;
import org.hopper.language.portugol.Model;
import org.hopper.language.portugol.OtherCase;
import org.hopper.language.portugol.PortugolPackage;
import org.hopper.language.portugol.ReadCommand;
import org.hopper.language.portugol.RepeatStatement;
import org.hopper.language.portugol.ReturnStatement;
import org.hopper.language.portugol.SubprogramParamDeclaration;
import org.hopper.language.portugol.Subprograms;
import org.hopper.language.portugol.SwitchCaseStatement;
import org.hopper.language.portugol.VarDeclaration;
import org.hopper.language.portugol.VarType;
import org.hopper.language.portugol.Variable;
import org.hopper.language.portugol.WhileStatement;
import org.hopper.language.portugol.WriteCommand;
import org.hopper.language.services.PortugolGrammarAccess;

@SuppressWarnings("all")
public class PortugolFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private PortugolGrammarAccess _portugolGrammarAccess;
  
  protected void _format(final Model model, @Extension final IFormattableDocument document) {
    HeaderBlock _header = model.getHeader();
    document.<HeaderBlock>format(_header);
    DeclarationsBlock _globalDeclarations = model.getGlobalDeclarations();
    document.<DeclarationsBlock>format(_globalDeclarations);
    Subprograms _subprograms = model.getSubprograms();
    document.<Subprograms>format(_subprograms);
    BlockCommand _commands = model.getCommands();
    document.<BlockCommand>format(_commands);
  }
  
  protected void _format(final HeaderBlock headerBlock, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(headerBlock);
    ISemanticRegion _keyword = _regionFor.keyword("algoritmo");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_keyword, _function);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(headerBlock);
    ParserRule _eND_COMMANDRule = this._portugolGrammarAccess.getEND_COMMANDRule();
    ISemanticRegion _ruleCallTo = _regionFor_1.ruleCallTo(_eND_COMMANDRule);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(_ruleCallTo, _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.<HeaderBlock>append(headerBlock, _function_2);
  }
  
  protected void _format(final DeclarationsBlock declarationsBlock, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(declarationsBlock);
    ISemanticRegion _keyword = _regionFor.keyword("var");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _append = document.append(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(_append, _function_1);
    final EList<Variable> vars = declarationsBlock.getVars();
    for (final Variable variable : vars) {
      {
        document.<Variable>format(variable);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<Variable>prepend(variable, _function_2);
      }
    }
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<DeclarationsBlock>interior(declarationsBlock, _function_2);
  }
  
  protected void _format(final Subprograms subprograms, @Extension final IFormattableDocument document) {
    EList<BlockSubPrograms> _blockSubPrograms = subprograms.getBlockSubPrograms();
    for (final BlockSubPrograms subprogram : _blockSubPrograms) {
      document.<BlockSubPrograms>format(subprogram);
    }
  }
  
  protected void _format(final BlockFunction blockFunction, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    document.<BlockFunction>surround(blockFunction, _function);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(blockFunction);
    ISemanticRegion _keyword = _regionFor.keyword("funcao");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_2);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(blockFunction);
    ISemanticRegion _keyword_1 = _regionFor_1.keyword("(");
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword_1, _function_3);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(blockFunction);
    ISemanticRegion _keyword_2 = _regionFor_2.keyword(")");
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(_keyword_2, _function_4);
    ISemanticRegionsFinder _regionFor_3 = this.textRegionExtensions.regionFor(blockFunction);
    ISemanticRegion _keyword_3 = _regionFor_3.keyword(":");
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.surround(_keyword_3, _function_5);
    DeclarationsBlock _declarations = blockFunction.getDeclarations();
    document.<DeclarationsBlock>format(_declarations);
    ISemanticRegionsFinder _regionFor_4 = this.textRegionExtensions.regionFor(blockFunction);
    final ISemanticRegion beginCommands = _regionFor_4.keyword("inicio");
    ISemanticRegionsFinder _regionFor_5 = this.textRegionExtensions.regionFor(blockFunction);
    final ISemanticRegion endCommands = _regionFor_5.keyword("fimfuncao");
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _surround = document.surround(beginCommands, _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _prepend_1 = document.prepend(_surround, _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(beginCommands, endCommands, _function_9);
    EList<AbstractCommand> _commands = blockFunction.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(endCommands, _function_10);
  }
  
  protected void _format(final BlockProcedure blockProcedure, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    document.<BlockProcedure>surround(blockProcedure, _function);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(blockProcedure);
    ISemanticRegion _keyword = _regionFor.keyword("procedimento");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_2);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(blockProcedure);
    ISemanticRegion _keyword_1 = _regionFor_1.keyword("(");
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword_1, _function_3);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(blockProcedure);
    ISemanticRegion _keyword_2 = _regionFor_2.keyword(")");
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(_keyword_2, _function_4);
    DeclarationsBlock _declarations = blockProcedure.getDeclarations();
    document.<DeclarationsBlock>format(_declarations);
    ISemanticRegionsFinder _regionFor_3 = this.textRegionExtensions.regionFor(blockProcedure);
    final ISemanticRegion beginCommands = _regionFor_3.keyword("inicio");
    ISemanticRegionsFinder _regionFor_4 = this.textRegionExtensions.regionFor(blockProcedure);
    final ISemanticRegion endCommands = _regionFor_4.keyword("fimprocedimento");
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _surround = document.surround(beginCommands, _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _prepend_1 = document.prepend(_surround, _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(beginCommands, endCommands, _function_8);
    EList<AbstractCommand> _commands = blockProcedure.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(endCommands, _function_9);
  }
  
  protected void _format(final Variable variable, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<Variable>surround(variable, _function);
    VarDeclaration _varDeclaration = variable.getVarDeclaration();
    document.<VarDeclaration>format(_varDeclaration);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(variable);
    ISemanticRegion _keyword = _regionFor.keyword(":");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.surround(_keyword, _function_1);
    VarType _type = variable.getType();
    document.<VarType>format(_type);
  }
  
  protected void _format(final VarType varType, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<VarType>surround(varType, _function);
  }
  
  protected void _format(final BlockCommand blockCommand, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.setNewLines(2);
    };
    BlockCommand _prepend = document.<BlockCommand>prepend(blockCommand, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<BlockCommand>append(_prepend, _function_1);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(blockCommand);
    final ISemanticRegion beginCommands = _regionFor.keyword("inicio");
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(blockCommand);
    final ISemanticRegion endCommands = _regionFor_1.keyword("fimalgoritmo");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _surround = document.surround(beginCommands, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_surround, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(beginCommands, endCommands, _function_4);
    EList<AbstractCommand> _commands = blockCommand.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.prepend(endCommands, _function_5);
  }
  
  protected void _format(final EList<AbstractCommand> commands, @Extension final IFormattableDocument document) {
    for (final AbstractCommand command : commands) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<AbstractCommand>prepend(command, _function);
        document.<AbstractCommand>format(command);
      }
    }
  }
  
  protected void _format(final ReadCommand readCommand, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<ReadCommand>surround(readCommand, _function);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(readCommand);
    ISemanticRegion _keyword = _regionFor.keyword("(");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(readCommand);
    ISemanticRegion _keyword_1 = _regionFor_1.keyword(")");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword_1, _function_2);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(readCommand);
    ParserRule _eND_COMMANDRule = this._portugolGrammarAccess.getEND_COMMANDRule();
    ISemanticRegion _ruleCallTo = _regionFor_2.ruleCallTo(_eND_COMMANDRule);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_ruleCallTo, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend, _function_4);
  }
  
  protected void _format(final WriteCommand writeCommand, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<WriteCommand>surround(writeCommand, _function);
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(writeCommand);
    ISemanticRegion _keyword = _regionFor.keyword("(");
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(writeCommand);
    ISemanticRegion _keyword_1 = _regionFor_1.keyword(")");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword_1, _function_2);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(writeCommand);
    ParserRule _eND_COMMANDRule = this._portugolGrammarAccess.getEND_COMMANDRule();
    ISemanticRegion _ruleCallTo = _regionFor_2.ruleCallTo(_eND_COMMANDRule);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_ruleCallTo, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend, _function_4);
  }
  
  protected void _format(final IfStatement ifStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(ifStatement);
    ISemanticRegion regionIfKeyword = _regionFor.keyword("se");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(regionIfKeyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(ifStatement);
    ISemanticRegion regionThenKeyword = _regionFor_1.keyword("entao");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionThenKeyword, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_3);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(ifStatement);
    ISemanticRegion regionEndifKeyword = _regionFor_2.keyword("fimse");
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.surround(regionEndifKeyword, _function_4);
    ISemanticRegionsFinder _regionFor_3 = this.textRegionExtensions.regionFor(ifStatement);
    ISemanticRegion regionElseKeyword = _regionFor_3.keyword("senao");
    boolean _notEquals = (!Objects.equal(regionElseKeyword, null));
    if (_notEquals) {
      final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
        it.newLine();
      };
      document.surround(regionElseKeyword, _function_5);
      final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
        it.indent();
      };
      document.<ISemanticRegion, ISemanticRegion>interior(regionThenKeyword, regionElseKeyword, _function_6);
      final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
        it.indent();
      };
      document.<ISemanticRegion, ISemanticRegion>interior(regionElseKeyword, regionEndifKeyword, _function_7);
      EList<AbstractCommand> _elseCommands = ifStatement.getElseCommands();
      document.<EList<AbstractCommand>>format(_elseCommands);
    } else {
      final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
        it.indent();
      };
      document.<ISemanticRegion, ISemanticRegion>interior(regionThenKeyword, regionEndifKeyword, _function_8);
    }
    EList<AbstractCommand> _commands = ifStatement.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
  }
  
  protected void _format(final SwitchCaseStatement switchCaseStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(switchCaseStatement);
    ISemanticRegion _keyword = _regionFor.keyword("escolha");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(switchCaseStatement);
    ISemanticRegion regionEndSwitch = _regionFor_1.keyword("fimescolha");
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(switchCaseStatement);
    ISemanticRegion regionVariableRef = _regionFor_2.feature(PortugolPackage.Literals.SWITCH_CASE_STATEMENT__VARIABLE);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionVariableRef, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.surround(regionEndSwitch, _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(regionVariableRef, regionEndSwitch, _function_5);
    EList<CaseList> _caseList = switchCaseStatement.getCaseList();
    final Consumer<CaseList> _function_6 = (CaseList it) -> {
      document.<CaseList>format(it);
    };
    _caseList.forEach(_function_6);
    OtherCase _otherCase = switchCaseStatement.getOtherCase();
    if (_otherCase!=null) {
      document.<OtherCase>format(_otherCase);
    }
  }
  
  protected void _format(final CaseList caseList, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(caseList);
    ISemanticRegion _keyword = _regionFor.keyword("caso");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    Expression _expr = caseList.getExpr();
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.<Expression>surround(_expr, _function_2);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(caseList);
    ISemanticRegion regionOpenCase = _regionFor_1.keyword(":");
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionOpenCase, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_4);
    EList<AbstractCommand> _commands = caseList.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<CaseList>interior(caseList, _function_5);
  }
  
  protected void _format(final OtherCase otherCase, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(otherCase);
    ISemanticRegion _keyword = _regionFor.keyword("outrocaso");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(otherCase);
    ISemanticRegion regionOpenOtherCase = _regionFor_1.keyword(":");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionOpenOtherCase, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_3);
    EList<AbstractCommand> _otherCaseCommands = otherCase.getOtherCaseCommands();
    document.<EList<AbstractCommand>>format(_otherCaseCommands);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<OtherCase>interior(otherCase, _function_4);
  }
  
  protected void _format(final BreakStatement breakStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(breakStatement);
    ISemanticRegion _keyword = _regionFor.keyword("interrompa");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.surround(_keyword, _function);
  }
  
  protected void _format(final ReturnStatement returnStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(returnStatement);
    ISemanticRegion _keyword = _regionFor.keyword("retorne");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    Expression _expr = returnStatement.getExpr();
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    Expression _prepend_1 = document.<Expression>prepend(_expr, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
      it.autowrap();
    };
    document.<Expression>append(_prepend_1, _function_3);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(returnStatement);
    ParserRule _eND_COMMANDRule = this._portugolGrammarAccess.getEND_COMMANDRule();
    ISemanticRegion _ruleCallTo = _regionFor_1.ruleCallTo(_eND_COMMANDRule);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend_2 = document.prepend(_ruleCallTo, _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_2, _function_5);
  }
  
  protected void _format(final VarDeclaration varDeclaration, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(varDeclaration);
    List<ISemanticRegion> _keywords = _regionFor.keywords(",");
    for (final ISemanticRegion commas : _keywords) {
      final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
        it.noSpace();
      };
      ISemanticRegion _prepend = document.prepend(commas, _function);
      final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
        it.autowrap();
      };
      document.append(_prepend, _function_1);
    }
  }
  
  protected void _format(final ForStatement forStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion _keyword = _regionFor.keyword("para");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    Expression _operatorExpr = forStatement.getOperatorExpr();
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.<Expression>surround(_operatorExpr, _function_2);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion _keyword_1 = _regionFor_1.keyword("de");
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.surround(_keyword_1, _function_3);
    Expression _startExpr = forStatement.getStartExpr();
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.<Expression>surround(_startExpr, _function_4);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion _keyword_2 = _regionFor_2.keyword("ate");
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.surround(_keyword_2, _function_5);
    Expression _endExpr = forStatement.getEndExpr();
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.<Expression>surround(_endExpr, _function_6);
    ISemanticRegionsFinder _regionFor_3 = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion _keyword_3 = _regionFor_3.keyword("passo");
    if (_keyword_3!=null) {
      final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
      };
      document.surround(_keyword_3, _function_7);
    }
    Expression _startExpr_1 = forStatement.getStartExpr();
    if (_startExpr_1!=null) {
      final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
      };
      document.<Expression>surround(_startExpr_1, _function_8);
    }
    ISemanticRegionsFinder _regionFor_4 = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion regionDoKw = _regionFor_4.keyword("faca");
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionDoKw, _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_10);
    EList<AbstractCommand> _commands = forStatement.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    ISemanticRegionsFinder _regionFor_5 = this.textRegionExtensions.regionFor(forStatement);
    ISemanticRegion regionEndFor = _regionFor_5.keyword("fimpara");
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.surround(regionEndFor, _function_11);
    final Procedure1<IHiddenRegionFormatter> _function_12 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(regionDoKw, regionEndFor, _function_12);
  }
  
  protected void _format(final RepeatStatement repeatStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(repeatStatement);
    ISemanticRegion regionRepeatKw = _regionFor.keyword("repita");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(regionRepeatKw, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend, _function_1);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(repeatStatement);
    ISemanticRegion regionUntilKw = _regionFor_1.keyword("ate");
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionUntilKw, _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend_1, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(regionRepeatKw, regionUntilKw, _function_4);
    EList<AbstractCommand> _commands = repeatStatement.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    Expression _untilExpr = repeatStatement.getUntilExpr();
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    Expression _prepend_2 = document.<Expression>prepend(_untilExpr, _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.<Expression>append(_prepend_2, _function_6);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(repeatStatement);
    ParserRule _eND_COMMANDRule = this._portugolGrammarAccess.getEND_COMMANDRule();
    ISemanticRegion _ruleCallTo = _regionFor_2.ruleCallTo(_eND_COMMANDRule);
    ISemanticRegion _prepend_3 = null;
    if (_ruleCallTo!=null) {
      final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
        it.noSpace();
      };
      _prepend_3=document.prepend(_ruleCallTo, _function_7);
    }
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_3, _function_8);
  }
  
  protected void _format(final WhileStatement whileStatement, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(whileStatement);
    ISemanticRegion _keyword = _regionFor.keyword("enquanto");
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    ISemanticRegion _prepend = document.prepend(_keyword, _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(_prepend, _function_1);
    Expression _whileExpr = whileStatement.getWhileExpr();
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.<Expression>surround(_whileExpr, _function_2);
    ISemanticRegionsFinder _regionFor_1 = this.textRegionExtensions.regionFor(whileStatement);
    ISemanticRegion regionDoKw = _regionFor_1.keyword("faca");
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    ISemanticRegion _prepend_1 = document.prepend(regionDoKw, _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.append(_prepend_1, _function_4);
    EList<AbstractCommand> _commands = whileStatement.getCommands();
    document.<EList<AbstractCommand>>format(_commands);
    ISemanticRegionsFinder _regionFor_2 = this.textRegionExtensions.regionFor(whileStatement);
    ISemanticRegion regionEndFor = _regionFor_2.keyword("fimenquanto");
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.newLine();
    };
    document.surround(regionEndFor, _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.indent();
    };
    document.<ISemanticRegion, ISemanticRegion>interior(regionDoKw, regionEndFor, _function_6);
  }
  
  protected void _format(final SubprogramParamDeclaration subprogramParamDeclaration, @Extension final IFormattableDocument document) {
    ISemanticRegionsFinder _regionFor = this.textRegionExtensions.regionFor(subprogramParamDeclaration);
    List<ISemanticRegion> _keywords = _regionFor.keywords(";");
    for (final ISemanticRegion variables : _keywords) {
      final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
        it.autowrap();
      };
      document.append(variables, _function);
    }
  }
  
  public void format(final Object commands, final IFormattableDocument document) {
    if (commands instanceof XtextResource) {
      _format((XtextResource)commands, document);
      return;
    } else if (commands instanceof EList) {
      _format((EList<AbstractCommand>)commands, document);
      return;
    } else if (commands instanceof BlockFunction) {
      _format((BlockFunction)commands, document);
      return;
    } else if (commands instanceof BlockProcedure) {
      _format((BlockProcedure)commands, document);
      return;
    } else if (commands instanceof BreakStatement) {
      _format((BreakStatement)commands, document);
      return;
    } else if (commands instanceof ForStatement) {
      _format((ForStatement)commands, document);
      return;
    } else if (commands instanceof IfStatement) {
      _format((IfStatement)commands, document);
      return;
    } else if (commands instanceof ReadCommand) {
      _format((ReadCommand)commands, document);
      return;
    } else if (commands instanceof RepeatStatement) {
      _format((RepeatStatement)commands, document);
      return;
    } else if (commands instanceof ReturnStatement) {
      _format((ReturnStatement)commands, document);
      return;
    } else if (commands instanceof SwitchCaseStatement) {
      _format((SwitchCaseStatement)commands, document);
      return;
    } else if (commands instanceof WhileStatement) {
      _format((WhileStatement)commands, document);
      return;
    } else if (commands instanceof WriteCommand) {
      _format((WriteCommand)commands, document);
      return;
    } else if (commands instanceof BlockCommand) {
      _format((BlockCommand)commands, document);
      return;
    } else if (commands instanceof CaseList) {
      _format((CaseList)commands, document);
      return;
    } else if (commands instanceof DeclarationsBlock) {
      _format((DeclarationsBlock)commands, document);
      return;
    } else if (commands instanceof HeaderBlock) {
      _format((HeaderBlock)commands, document);
      return;
    } else if (commands instanceof Model) {
      _format((Model)commands, document);
      return;
    } else if (commands instanceof OtherCase) {
      _format((OtherCase)commands, document);
      return;
    } else if (commands instanceof SubprogramParamDeclaration) {
      _format((SubprogramParamDeclaration)commands, document);
      return;
    } else if (commands instanceof Subprograms) {
      _format((Subprograms)commands, document);
      return;
    } else if (commands instanceof VarDeclaration) {
      _format((VarDeclaration)commands, document);
      return;
    } else if (commands instanceof VarType) {
      _format((VarType)commands, document);
      return;
    } else if (commands instanceof Variable) {
      _format((Variable)commands, document);
      return;
    } else if (commands instanceof EObject) {
      _format((EObject)commands, document);
      return;
    } else if (commands == null) {
      _format((Void)null, document);
      return;
    } else if (commands != null) {
      _format(commands, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(commands, document).toString());
    }
  }
}
